const stepThree = {
    namespaced: true,
    state: {
        availableInternetProviders: "",
        availableTVProviders: "",
        availablePhoneProviders: "",
        newStreetAddress: "",
        newCity: "",
        newState: "",
        newZipCode: "",
        internetCheckbox: "",
        tvCheckbox: "",
        phoneCheckbox: "",
        noneCheckbox: "",
        internetName: "",
        selectedInternetProvider: "",
        internetPlan: "",
        previousStreet: "",
        previousCity: "",
        previousState: "",
        previousZipCode: "",
        previousCountry: "United States",
        InstallationTypeInternet: "",
        anyPets: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
        newState: "",
    },
    mutations: {

    }
};
export default stepThree;