const stepThree = {
    namespaced: true,
    state: {
        availableInternetProviders: "",
        availableTVProviders: "",
        availablePhoneProviders: "",
        newStreetAddress: "",
        newCity: "",
        newState: "",
        newZipCode: "",
        internetCheckbox: "",
        tvCheckbox: "",
        phoneCheckbox: "",
        noneCheckbox: "",
        internetName: "",
        selectedInternetProvider: "",
        internetPlan: "",
        previousStreet: "",
        previousCity: "",
        previousState: "",
        previousZipCode: "",
        previousCountry: "United States",
        InstallationTypeInternet: "",
        anyPets: "",
        
        internetInstallTime: "",
        securityQuestion: "",
        securityAnswer: "",
        securityPin: "",
        internetAccountWorkorder: "",
        mobilePhoneProvider: "",
        noMobileLines: "",
        mobileNotes: "",
        selectedTV: "",
        otherTV: "",
        whosNameWillTv: "",
        tvEssentials: "",
        tvPlanEquipment: "",
        installationTypeSelected: "",
        tvInstallTime: "",
        securityQuestionTV: "",
        securityAnswerTv: "",
        securityPinTv: "",
        tvAccountWorkorder: "",
        selectedPhone: "",
        otherPhone: "",
        whosNameWillPhone: "",
        phonePlanEquipment: "",
        installationTypePhone: "",
        phoneInstallTime: "",
        securityQuestionPhone: "",
        securityAnswerPhone: "",
        securityPinPhone: "",
        phoneAccountNumber: "",
        primarySSN: "",
        last4ofSSN: "",
        secondarySSNforcable: "",
        collectCCInfo: "",
        cardType: "",
        CCNumber: "",
        expiration: "",
        NameonCard: "",
        billingZipCode: "",
        cardVerificationCode: "",
        createTicketInternet: "",
        createTicketTV: "",
        ticketNotes: "",
        ihaveReviewed: "",
        internetInstallDateFormattedStore: "",
        mobileActivationDateFormattedStore:"",
        tvInstallDateFormattedStore: "",
        phoneInstallDateFormattedStore:"",
        primaryBirthDateFormattedStore:"",
        secondaryBirthDateFormattedStore:""


    },
    mutations: {

    }
};
export default stepThree;