const stepSeven = {
    namespaced: true,
    state: {
        availablePowerProviders:'',
        whoIsNameWillElectric:'',
        electricProviderActived:'',
        activationOeTransfer:'',
        primarySSN:'',
        secondarySSNForPower:'',
        dlForPower:'',
        employerNameBusiness:'',
        haveSupportKeyElectric:'',
        ticketNotes:'',
        fplSurgesShield:'',
        availableGasProviders:'',
        whosNameWillGas:'',
        gasProviderActivated:'',
        primarySSN2:'',
        secondarySSN:'',
        haveSupportKeyGas:'',
        ticketNotes2:'',
        
        
        primaryDOBMenu:'',
        primaryDOBFormated:'',
        primaryDOBDate:'',
        secondaryDOBMenu:'',
        secondaryDOBFormated:'',
        secondaryDOBDate:'',
        electricActivationMenu:'',
        electricActivationFormated:'',
        electricActivationDate:'',
        electricCancellationMenu:'',
        electricCancellationFormated:'',
        electricCancellationDate:'',
        gasActivationMenu:'',
        gasActivationFormated:'',
        gasActivationDate:'',
        primaryDOBMenu2:'',
        primaryDOBFormated2:'',
        primaryDOBDate2:'',
        secondDOBMenu2:'',
        secondDOBFormated2:'',
        secondDOBDate2:'',
    },
    mutations: {

    }
};
export default stepSeven;